# Fedora stage for fonts
FROM registry.fedoraproject.org/fedora:latest AS fonts
RUN dnf install -y unzip ibm-plex-*-fonts ipa*-fonts mrsw-biz-*-fonts \
  && curl -L -O https://github.com/yuru7/udev-gothic/releases/download/v2.1.0/UDEVGothic_NF_v2.1.0.zip \
  && unzip UDEVGothic_NF_v2.1.0.zip -d /usr/share/fonts/ \
  && rm -f UDEVGothic_NF_v2.1.0.zip

# Main stage
FROM ghcr.io/typst/typst:0.14.0

# Copy fonts from Fedora stage
COPY --from=fonts /usr/share/fonts /usr/share/fonts
